// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpNuY0jpT-HC4P2NOpwtbk06VlFXCkh_8',
    appId: '1:457935951014:web:ca800b843829a2e2b9d067',
    messagingSenderId: '457935951014',
    projectId: 'gausampada-gdg',
    authDomain: 'gausampada-gdg.firebaseapp.com',
    storageBucket: 'gausampada-gdg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA5BK-h6_WgJHReB-nY0Op4PRDa-t7KLw',
    appId: '1:457935951014:android:e725e3d11ae7cab1b9d067',
    messagingSenderId: '457935951014',
    projectId: 'gausampada-gdg',
    storageBucket: 'gausampada-gdg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYkJL9H9XmP44kdS-1PS10F-K-Vm0QlE',
    appId: '1:457935951014:ios:5cf18b4b831f5098b9d067',
    messagingSenderId: '457935951014',
    projectId: 'gausampada-gdg',
    storageBucket: 'gausampada-gdg.firebasestorage.app',
    iosBundleId: 'com.example.gausampada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALYkJL9H9XmP44kdS-1PS10F-K-Vm0QlE',
    appId: '1:457935951014:ios:5cf18b4b831f5098b9d067',
    messagingSenderId: '457935951014',
    projectId: 'gausampada-gdg',
    storageBucket: 'gausampada-gdg.firebasestorage.app',
    iosBundleId: 'com.example.gausampada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpNuY0jpT-HC4P2NOpwtbk06VlFXCkh_8',
    appId: '1:457935951014:web:3165764f44e69635b9d067',
    messagingSenderId: '457935951014',
    projectId: 'gausampada-gdg',
    authDomain: 'gausampada-gdg.firebaseapp.com',
    storageBucket: 'gausampada-gdg.firebasestorage.app',
  );
}
